// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Search() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"min-h-screen bg-gray-100 flex justify-center p-2 md:p-6\"><section class=\"card w-full max-w-[2000px] bg-white\"><div class=\"card-body w-full p-4 md:p-6\" hx-ext=\"client-side-templates\" nunjucks-template=\"resultsTemplate\"><div class=\"flex gap-8 flex-col lg:flex-row\"><h1 class=\"font-bold text-3xl text-center pt-1\">goSearch</h1><form hx-post=\"/api/v1/search\" hx-target=\"#results\" hx-indicator=\"#indicator\" hx-disabled-elt=\"find button[type=&#39;submit&#39;]\" hx-target-error=\"#results\" class=\"w-full\"><div class=\"flex flex-col gap-4 md:flex-row \"><input type=\"text\" name=\"query\" class=\"input input-bordered w-full lg:w-1/2\" placeholder=\"Search...\"> <button class=\"btn btn-primary\" type=\"submit\" data-testid=\"searchBtn\">Search</button></div><div id=\"indicator\" class=\"htmx-indicator\"><div class=\"w-full flex justify-center items-center mt-2\"><span class=\"loading loading-spinner loading-md text-primary\"></span></div></div></form></div><div id=\"results\" class=\"w-full lg:pl-[10.5rem]\"></div></div></section><!-- Nunjucks Template for Results --><script type=\"text/nunjucks\" id=\"resultsTemplate\">\n        <p class=\"text-sm text-gray-500 pb-2\">Total results: {{ total }}</p>\n\t\t\t\t<ul class=\"list-none\">\n\t\t\t\t\t{% for result in results %}\n\t\t\t\t\t\t<li class=\"mb-6 overflow-x-auto\">\n              <h2 class=\"card-title\">\n                <a href=\"{{ result.url }}\" class=\"link link-hover\" target=\"_blank\">\n                  {{ result.title or result.headings or \"No title\" }}\n                </a>\n              </h2>\n              <p class=\"text-gray-500\">{{ result.description }}</p>\n              <a href=\"{{ result.url }}\" class=\"link link-hover text-sm\" target=\"_blank\">{{ result.url }}</a>\n\t\t\t\t\t\t</li>\n\t\t\t\t\t{% endfor %}\n\t\t\t\t</ul>\n\t\t\t</script></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Index().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
